package layout

object TeamDataModel {
    val teamList = listOf<Team>(
        Team("Alabama", "Yellowhammer State", "50,744 miles"),
        Team("Alaska", "The Last Frontier", "571,951 miles"),
        Team("Arizona", "The Grand Canyon State", "113,635 miles"),
        Team("Arkansas", "The Natural State", "52,068 miles"),
        Team("California", "The Golden State", "155,959 miles"),
        Team("Colorado", "The Centennial State", "103,718 miles"),
        Team("Connecticut", "The Constitution State", "4,845 miles"),
        Team("Delaware", "The First State", "1,954 miles"),
        Team("Florida", "The Sunshine State", "53,927 miles"),
        Team("Georgia", "The Peach State", "57,906 miles"),
        Team("Hawaii", "The Aloha State", "6,423 miles"),
        Team("Idaho", "The Gem State", "82,747 miles"),
        Team("Illinois", "Prairie State", "55,584 miles"),
        Team("Indiana", "The Hoosier State", "35,867 miles"),
        Team("Iowa", "The Hawkeye State", "55,869 miles"),
        Team("Kansas", "The Sunflower State", "81,815 miles"),
        Team("Kentucky", "The Bluegrass State", "39,728 miles"),
        Team("Louisiana", "The Pelican State", "3,562 miles"),
        Team("Maine", "The Pine Tree State", "30,862 miles"),
        Team("Maryland", "The Old Line State", "9,774 miles"),
        Team("Massachusetts", "The Bay State", "7,840 miles"),
        Team("Michigan", "The Great Lakes State", "56,804 miles"),
        Team("Minnesota", "The North Star State", "79,610 miles"),
        Team("Mississippi", "The Magnolia State", "46,907 miles"),
        Team("Missouri", "The Show Me State", "68,886 miles"),
        Team("Montana", "The Treasure State", "145,552 miles"),
        Team("Nebraska", "The Cornhusker State", "76,872 miles"),
        Team("Nevada", "The Silver State", "109,826 miles"),
        Team("New Hampshire", "The Granite State", "8,968 miles"),
        Team("New Jersey", "The Garden State", "7,417 miles"),
        Team("New Mexico", "The Land of Enchantment", "121,356 miles"),
        Team("New York", "The Empire State", "47,214 miles"),
        Team("North Carolina", "The Tar Heel State", "48,711 miles"),
        Team("North Dakota", "The Peace Garden State", "68,976 miles"),
        Team("Ohio", "The Buckeye State", "40,948 miles"),
        Team("Oklahoma", "The Sooner State", "68,667 miles"),
        Team("Oregon", "The Beaver State", "95,997 miles"),
        Team("Pennsylvania", "The Keystone State", "44,817 miles"),
        Team("Rhode Island", "The Ocean State", "1,045 miles"),
        Team("South Carolina", "The Palmetto State", "30,109 miles"),
        Team("South Dakota", "Mount Rushmore State", "75,885 miles"),
        Team("Tennessee", "The Volunteer State", "41,217 miles"),
        Team("Texas", "The Lone Star State", "261,797 miles"),
        Team("Utah", "The Beehive State", "82,144 miles"),
        Team("Vermont", "The Green Mountain State", "9,250 miles"),
        Team("Virginia", "The Old Dominion State", "39,594 miles"),
        Team("Washington", "The Evergreen State", "66,544 miles"),
        Team("West Virginia", "The Mountain State", "24,078 miles"),
        Team("Wisconsin", "The Badger State", "54,310 miles"),
        Team("Wyoming", "The Equality or Cowboy State", "97,100 miles")
    )
}